#!/bin/sh

version="0.0.1"

pkg_name="restli-$version"
tar_file="$pkg_name.tar.gz"

for packaging in modular bundled; do
  mkdir -p "dist/$packaging/$pkg_name"
  cp -r bin/$packaging/* "dist/$packaging/$pkg_name"
  pushd dist/$packaging
  echo "creating $packaging/$tar_file"
  tar -czf $tar_file $pkg_name
  popd
done

mkdir -p rpmbuild/SOURCES
cp dist/bundled/$tar_file rpmbuild/SOURCES/$tar_file
rpmbuild/build-rpm
