#!/bin/sh

version="0.0.1"
pkg_name="restli-$version"
tar_file="$pkg_name.tar.gz"

mkdir -p "dist/$pkg_name"
cp -r bin/* "dist/$pkg_name"
pushd dist
echo "creating $tar_file"
tar -czf $tar_file $pkg_name
popd

mkdir -p rpmbuild/SOURCES
cp dist/$tar_file rpmbuild/SOURCES/$tar_file
rpmbuild/build-rpm
